COLUMN_NAME = "sqlalchemy.sql.schema.Column"
GROUPING_NAME = "sqlalchemy.sql.elements.Grouping"
GINO_NAME = "flask_sqlalchemy.SQLAlchemy"
RELATIONSHIP_NAME = "sqlalchemy.orm.relationships.RelationshipProperty"
DECLARATIVE_BASE_NAME = "flask_sqlalchemy.SQLAlchemy.make_declarative_base"
